### ISSUE TITLE
move pam_u2f to ::gentoo

### ISSUE THREAD

**Issue by gktrk** [Shirk/gentoo-u2f-overlay#3]
Hi, I am thinking about maintaining pam_u2f in the main Gentoo tree. Would you be interested in co-maintaining it with me?

**Comment by HealsCodes** [comment]
Sure, this package is pretty low on maintenance as it is.
Would be cool to have it in main tree :thumbsup:

**Comment by gktrk** [comment]
Here's what I will be committing to the tree: https://github.com/gktrk/gentoo/compare/master...gktrk:u2f
- Bumped both ebuilds to EAPI 6
- For pam_u2f, renamed pam-debug to debug since we explain it as part of the local USE flag description in the metadata. Removed the debug patch and replaced it with flag-o-matic.
- Both ebuilds will be keyworded for x86. We need libu2f-host keyworded for x86 first since it is a dep. I contacted the crypto project about it already.

How would you like to be included in the metadata? I have put you first in the list which means you will be responsible for the bugs against the package and I will be CC'd to them. Let me know if you have a particular <name/> and <email/> preference.

**Comment by HealsCodes** [comment]
Sorry for the delay.. I was pretty busy the last weeks.
Great job on the changes to get the ebuilds more in line with mainstream!

Regarding the list order I don't mind either - I think I can cope with bugs against the package 👍

**Comment by gktrk** [comment]
Cool! Do you have a particular &lt;name/&gt; and &lt;email/&gt; preference for the metadata?

**Comment by HealsCodes** [comment]
Nope, that's scattered over the overlay already:

```
<name>René Köcher</name>
<email>shirk+gentoo@bitspin.org</email>
```

**Comment by gktrk** [comment]
In the tree: https://github.com/gentoo/gentoo/commit/aab1c58653908468c8182326c1775ae57e38f00d https://github.com/gentoo/gentoo/commit/d629f9fe9e99dc983188295b2d4be2ed7eeff494

Thanks!

**Comment by gktrk** [comment]
There needs to be a bugzilla account associated with the email address so the bugs can be assigned to you. Looks like you are registered with 'shirk@bitspin.org'. Do you want to change your bugzilla email or the email address in the metadata?

**Comment by HealsCodes** [comment]
Oh.. the bugzilla, yes of course! I updated my mail address there to match the +gentoo tag - we're good to go.
